api_platform:
    title: Europa Football API
    description: API REST Europa Football permet de gerer les CRUD des entités pour une future interface visuelle de la page web Europa Football
    version: 1.0.0
    defaults:
        stateless: true
        pagination_items_per_page: 10
        maximum_items_per_page: 100
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    formats:
        json:
            mime_types: [ 'application/json' ]
        jsonld:
            mime_types: [ 'application/ld+json' ]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header